-- 1. Метаданные для колонки LOCATION в таблице FLOWER_SHOP
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES ('FLOWER_SHOP', 'LOCATION', 
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.00005),  -- Долгота: -180° до +180°, точность 5м
    SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.00005)     -- Широта: -90° до +90°, точность 5м
  ), 
  4326
);

-- 2. Метаданные для колонки COVERAGE_AREA в таблице FLOWER_SHOP
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES ('FLOWER_SHOP', 'COVERAGE_AREA', 
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.00005),
    SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.00005)
  ), 
  4326
);

-- 3. Метаданные для колонки CURRENT_LOCATION в таблице COURIER
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES ('COURIER', 'CURRENT_LOCATION', 
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.00005),
    SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.00005)
  ), 
  4326
);

-- 4. Метаданные для колонки DELIVERY_LOCATION в таблице USER_ORDER
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID)
VALUES ('USER_ORDER', 'DELIVERY_LOCATION', 
  SDO_DIM_ARRAY(
    SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.00005),
    SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.00005)
  ), 
  4326
);

COMMIT;