-- Удаляем старые индексы, если они существуют
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX HEAD_ADMIN.IDX_FLOWER_SHOP_LOCATION';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX HEAD_ADMIN.IDX_FLOWER_SHOP_COVERAGE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX HEAD_ADMIN.IDX_COURIER_LOCATION';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX HEAD_ADMIN.IDX_ORDER_DELIVERY_LOC';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 1. Индекс для местоположения магазинов (точки)
CREATE INDEX IDX_FLOWER_SHOP_LOCATION ON HEAD_ADMIN.FLOWER_SHOP(LOCATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('LAYER_GTYPE=POINT CBTREE_INDEX=TRUE');

-- 2. Индекс для зон доставки магазинов (полигоны)
CREATE INDEX IDX_FLOWER_SHOP_COVERAGE ON HEAD_ADMIN.FLOWER_SHOP(COVERAGE_AREA)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('LAYER_GTYPE=POLYGON');

-- 3. Индекс для текущего местоположения курьеров
CREATE INDEX IDX_COURIER_LOCATION ON HEAD_ADMIN.COURIER(CURRENT_LOCATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('LAYER_GTYPE=POINT');

-- 4. Индекс для точек доставки заказов
CREATE INDEX IDX_ORDER_DELIVERY_LOC ON HEAD_ADMIN.USER_ORDER(DELIVERY_LOCATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('LAYER_GTYPE=POINT');

-- 5. Обычные индексы для производительности
CREATE INDEX IDX_PRODUCT_NAME ON HEAD_ADMIN.PRODUCT(PRODUCT_NAME);
CREATE INDEX IDX_PRODUCT_ACTIVE ON HEAD_ADMIN.PRODUCT(IS_ACTIVE);
CREATE INDEX IDX_FLOWER_SHOP_ACTIVE ON HEAD_ADMIN.FLOWER_SHOP(IS_ACTIVE);
CREATE INDEX IDX_ORDER_STATUS ON HEAD_ADMIN.USER_ORDER(STATUS);
CREATE INDEX IDX_ORDER_DATE ON HEAD_ADMIN.USER_ORDER(ORDER_DATE);
CREATE INDEX IDX_COURIER_AVAILABLE ON HEAD_ADMIN.COURIER(IS_ACTIVE, IS_AVAILABLE);

COMMIT;

-- Проверка создания индексов
SELECT '=== ПРОСТРАНСТВЕННЫЕ ИНДЕКСЫ ===' as INFO FROM DUAL;
SELECT INDEX_NAME, TABLE_NAME, INDEX_TYPE, STATUS
FROM USER_INDEXES 
WHERE INDEX_NAME LIKE 'IDX_%' 
ORDER BY TABLE_NAME, INDEX_NAME;

SELECT '=== ПРОВЕРКА SPATIAL ИНДЕКСОВ ===' as INFO FROM DUAL;
SELECT INDEX_NAME, TABLE_NAME 
FROM USER_SDO_INDEX_INFO 
ORDER BY TABLE_NAME;