-- 1. Таблица ролей
CREATE TABLE USER_ROLE
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ROLE_NAME VARCHAR2(30) NOT NULL CHECK (ROLE_NAME IN ('head_admin', 'shop_admin', 'user'))
);

-- 2. Таблица персональных данных
CREATE TABLE PERSONAL_DATA
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  FULL_NAME NVARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(70) UNIQUE NOT NULL,
  PHONE_NUMBER VARCHAR2(30) UNIQUE NOT NULL,
  DATE_OF_BIRTH DATE
);

-- 3. Таблица пользователей
CREATE TABLE APP_USER
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PASSWORD_HASH VARCHAR2(300) NOT NULL,
    USER_ROLE INT NOT NULL,
    PERSONAL_DATA INT NOT NULL,
    CONSTRAINT FK_APP_USER_USER_ROLE FOREIGN KEY (USER_ROLE) REFERENCES USER_ROLE(ID),
    CONSTRAINT FK_APP_USER_PERSONAL_DATA FOREIGN KEY (PERSONAL_DATA) REFERENCES PERSONAL_DATA(ID)
);

-- 4. Таблица товаров (букетов)
CREATE TABLE PRODUCT
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  PRODUCT_NAME NVARCHAR2(255) NOT NULL,
  BASE_PRICE NUMBER(10, 2) NOT NULL CHECK (BASE_PRICE > 0),
  DESCRIPTION NVARCHAR2(1000),
  PRODUCT_IMAGE VARCHAR2(255),
  IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1))
);

-- 5. Таблица размерных категорий
CREATE TABLE SIZE_CATEGORY
(
  ID SMALLINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  SIZE_NAME VARCHAR2(50) NOT NULL UNIQUE,
  ITEM_SIZE NUMBER(4, 2) NOT NULL CHECK (ITEM_SIZE > 0),
  MARKUP NUMBER(4, 2) NOT NULL CHECK (MARKUP > 0)
);

-- 6. Таблица связи товаров и размеров
CREATE TABLE PRODUCT_ITEM_INFO
(
   ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
   PRODUCT_ID INT NOT NULL,
   SIZE_ID SMALLINT NOT NULL,
   CONSTRAINT FK_PRODUCT_ITEM_INFO_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
   CONSTRAINT FK_PRODUCT_ITEM_INFO_SIZE FOREIGN KEY (SIZE_ID) REFERENCES SIZE_CATEGORY(ID),
   CONSTRAINT UQ_PRODUCT_SIZE UNIQUE (PRODUCT_ID, SIZE_ID)
);

-- 7. Таблица корзин
CREATE TABLE CART
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  USER_ID INT UNIQUE NOT NULL,
  CONSTRAINT FK_CART_APP_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

-- 8. Таблица элементов корзины
CREATE TABLE CART_ITEM
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CART_ID INT NOT NULL,
    ITEM_INFO_ID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (CART_ID) REFERENCES CART(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_ITEM_ITEM_INFO FOREIGN KEY (ITEM_INFO_ID) REFERENCES PRODUCT_ITEM_INFO(ID)
);

-- 9. Таблица цветочных магазинов С SPATIAL
CREATE TABLE FLOWER_SHOP
(
  ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  SHOP_NAME NVARCHAR2(100) NOT NULL,
  ADDRESS NVARCHAR2(200) NOT NULL UNIQUE,
  LOCATION SDO_GEOMETRY NOT NULL,
  COVERAGE_AREA SDO_GEOMETRY NOT NULL,
  SHOP_ADMIN_ID INT UNIQUE NOT NULL,
  OPEN_TIME TIMESTAMP NOT NULL,
  CLOSE_TIME TIMESTAMP NOT NULL,
  DELIVERY_START_TIME TIMESTAMP NOT NULL,
  DELIVERY_END_TIME TIMESTAMP NOT NULL,
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(100),
  IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
  CONSTRAINT FK_FLOWER_SHOP_ADMIN FOREIGN KEY (SHOP_ADMIN_ID) REFERENCES APP_USER(ID)
);

-- 10. Таблица курьеров
CREATE TABLE COURIER
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PERSONAL_DATA_ID INT NOT NULL,
    SALARY NUMBER(10, 2) NOT NULL CHECK (SALARY > 0),
    FLOWER_SHOP_ID INT NOT NULL,
    VEHICLE_TYPE VARCHAR2(50),
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1)),
    IS_AVAILABLE NUMBER(1) DEFAULT 1 CHECK (IS_AVAILABLE IN (0, 1)),
    CURRENT_LOCATION SDO_GEOMETRY,
    LAST_ACTIVE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_COURIER_PERSONAL_DATA FOREIGN KEY (PERSONAL_DATA_ID) REFERENCES PERSONAL_DATA(ID),
    CONSTRAINT FK_COURIER_FLOWER_SHOP FOREIGN KEY (FLOWER_SHOP_ID) REFERENCES FLOWER_SHOP(ID) ON DELETE CASCADE
);

-- 11. Таблица заказов
CREATE TABLE USER_ORDER
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ORDER_NUMBER VARCHAR2(50) UNIQUE NOT NULL,
    USER_ID INT NOT NULL,
    FLOWER_SHOP_ID INT NOT NULL,
    DELIVERY_ADDRESS NVARCHAR2(200) NOT NULL,
    DELIVERY_LOCATION SDO_GEOMETRY NOT NULL,
    COURIER_ID INT,
    STATUS VARCHAR2(50) DEFAULT 'NEW' CHECK (STATUS IN ('NEW', 'PROCESSING', 'ASSIGNED', 'DELIVERING', 'DELIVERED', 'CANCELLED')),
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL CHECK (TOTAL_AMOUNT >= 0),
    ORDER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DELIVERY_DATE TIMESTAMP,
    NOTES NVARCHAR2(1000),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_ORDER_SHOP FOREIGN KEY (FLOWER_SHOP_ID) REFERENCES FLOWER_SHOP(ID),
    CONSTRAINT FK_ORDER_COURIER FOREIGN KEY (COURIER_ID) REFERENCES COURIER(ID)
);

-- 12. Таблица элементов заказа
CREATE TABLE ORDER_ITEM
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    ITEM_INFO_ID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE NUMBER(10, 2) NOT NULL CHECK (UNIT_PRICE > 0),
    SUBTOTAL NUMBER(10, 2) GENERATED ALWAYS AS (UNIT_PRICE * QUANTITY) VIRTUAL,
    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES USER_ORDER(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_ITEM_INFO FOREIGN KEY (ITEM_INFO_ID) REFERENCES PRODUCT_ITEM_INFO(ID)
);
