select * from HEAD_ADMIN.product;

select * from HEAD_ADMIN.flower_shop;

select * from HEAD_ADMIN.personal_data;

select * from HEAD_ADMIN.user_order;

select count(*) from product;


SELECT 
    AU.ID,
    PD.FULL_NAME,
    UR.ROLE_NAME,
    C.ID
FROM HEAD_ADMIN.APP_USER AU
JOIN HEAD_ADMIN.PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID
JOIN HEAD_ADMIN.USER_ROLE UR ON AU.USER_ROLE = UR.ID
LEFT JOIN HEAD_ADMIN.CART C ON AU.ID = C.USER_ID
WHERE UR.ROLE_NAME = 'user'
ORDER BY AU.ID;


-- Просмотр корзины с товарами
SELECT 
    CI.ID AS CART_ITEM_ID,
    CI.CART_ID,
    CI.QUANTITY,
    P.ID AS PRODUCT_ID,
    P.PRODUCT_NAME,
    SC.SIZE_NAME,
    P.BASE_PRICE,
    ROUND(P.BASE_PRICE * SC.MARKUP, 2) AS UNIT_PRICE,
    ROUND(P.BASE_PRICE * SC.MARKUP * CI.QUANTITY, 2) AS SUBTOTAL
FROM HEAD_ADMIN.CART_ITEM CI
JOIN HEAD_ADMIN.PRODUCT_ITEM_INFO PII ON CI.ITEM_INFO_ID = PII.ID
JOIN HEAD_ADMIN.PRODUCT P ON PII.PRODUCT_ID = P.ID
JOIN HEAD_ADMIN.SIZE_CATEGORY SC ON PII.SIZE_ID = SC.ID
WHERE CI.CART_ID = 58
ORDER BY CI.ID;



BEGIN
    HEAD_ADMIN.EXPORT_PRODUCTS_TO_JSON('test1.json');
END;
/


BEGIN
    HEAD_ADMIN.IMPORT_PRODUCTS_FROM_JSON('test1.json');
END;
/







































SELECT * FROM HEAD_ADMIN.APP_USER WHERE ID = 81; 


-- Только корзины, в которых есть товары
SELECT 
    CI.CART_ID,
    C.USER_ID,
    PD.FULL_NAME,
    PD.EMAIL,
    COUNT(CI.ID) AS DIFFERENT_ITEMS,
    SUM(CI.QUANTITY) AS TOTAL_QUANTITY
FROM HEAD_ADMIN.CART_ITEM CI
JOIN HEAD_ADMIN.CART C ON CI.CART_ID = C.ID
JOIN HEAD_ADMIN.APP_USER U ON C.USER_ID = U.ID
JOIN HEAD_ADMIN.PERSONAL_DATA PD ON U.PERSONAL_DATA = PD.ID
GROUP BY CI.CART_ID, C.USER_ID, PD.FULL_NAME, PD.EMAIL
ORDER BY CI.CART_ID;


---- Поиск корзины по id пользователя
--SELECT 
--    C.ID AS CART_ID,
--    U.ID AS USER_ID,
--    PD.FULL_NAME,
--    PD.EMAIL,
--    PD.ID AS PERSONAL_DATA_ID
--FROM HEAD_ADMIN.CART C
--JOIN HEAD_ADMIN.APP_USER U ON C.USER_ID = U.ID
--JOIN HEAD_ADMIN.PERSONAL_DATA PD ON U.PERSONAL_DATA = PD.ID
--WHERE U.ID = 50;


-- Под head_admin_con выполните:
GRANT SELECT, UPDATE ON HEAD_ADMIN.USER_ORDER TO SHOP_ADMIN;
GRANT SELECT, UPDATE ON HEAD_ADMIN.COURIER TO SHOP_ADMIN;
GRANT SELECT ON HEAD_ADMIN.USER_ORDER TO CUSTOMER;