CREATE OR REPLACE TYPE HEAD_ADMIN.RECORD_ORDER AS OBJECT
(
    ID            INT,
    ORDER_NUMBER  VARCHAR2(50),
    ORDER_DATE    VARCHAR2(50),
    USER_ID       INT,
    ADDRESS       NVARCHAR2(200),
    STATUS        VARCHAR2(50),
    TOTAL_AMOUNT  NUMBER(10, 2),
    SHOP_NAME     NVARCHAR2(100)
);
/

CREATE OR REPLACE TYPE HEAD_ADMIN.TABLE_ORDER AS TABLE OF RECORD_ORDER;
/

CREATE OR REPLACE TYPE HEAD_ADMIN.RECORD_ORDER_ITEM AS OBJECT
(
    ID            INT,
    ORDER_ID      INT,
    PRODUCT_ID    INT,
    PRODUCT_NAME  NVARCHAR2(255),
    SIZE_NAME     VARCHAR2(50),
    UNIT_PRICE    NUMBER(10, 2),
    QUANTITY      INT,
    SUBTOTAL      NUMBER(10, 2)
);
/

CREATE OR REPLACE TYPE HEAD_ADMIN.TABLE_ORDER_ITEM AS TABLE OF RECORD_ORDER_ITEM;
/

CREATE OR REPLACE TYPE HEAD_ADMIN.RECORD_CART_ITEM AS OBJECT
(
    ID            INT,
    CART_ID       INT,
    PRODUCT_ID    INT,
    PRODUCT_NAME  NVARCHAR2(255),
    SIZE_NAME     VARCHAR2(50),
    UNIT_PRICE    NUMBER(10, 2),
    QUANTITY      INT,
    SUBTOTAL      NUMBER(10, 2)
);
/

CREATE OR REPLACE TYPE HEAD_ADMIN.TABLE_CART_ITEM AS TABLE OF RECORD_CART_ITEM;
/

CREATE OR REPLACE TYPE HEAD_ADMIN.RECORD_ITEM_DETAIL AS OBJECT
(
    ITEM_ID       INT,
    PRODUCT_ID    INT,
    PRODUCT_NAME  NVARCHAR2(255),
    SIZE_ID       SMALLINT,
    SIZE_NAME     VARCHAR2(50),
    BASE_PRICE    NUMBER(10, 2),
    MARKUP        NUMBER(4, 2),
    FINAL_PRICE   NUMBER(10, 2)
);
/

CREATE OR REPLACE TYPE HEAD_ADMIN.TABLE_ITEM_DETAIL AS TABLE OF RECORD_ITEM_DETAIL;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('=== ТИПЫ ДАННЫХ СОЗДАНЫ ===');
    DBMS_OUTPUT.PUT_LINE('1. RECORD_ORDER');
    DBMS_OUTPUT.PUT_LINE('2. TABLE_ORDER');
    DBMS_OUTPUT.PUT_LINE('3. RECORD_ORDER_ITEM');
    DBMS_OUTPUT.PUT_LINE('4. TABLE_ORDER_ITEM');
    DBMS_OUTPUT.PUT_LINE('5. RECORD_CART_ITEM');
    DBMS_OUTPUT.PUT_LINE('6. TABLE_CART_ITEM');
    DBMS_OUTPUT.PUT_LINE('7. RECORD_ITEM_DETAIL');
    DBMS_OUTPUT.PUT_LINE('8. TABLE_ITEM_DETAIL');
END;
/