-- 1. Профиль безопасности
CREATE PROFILE USERS_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 3
    PASSWORD_REUSE_TIME 10
    CONNECT_TIME 180
    IDLE_TIME 60;

-- 2. Базовая роль (для всех пользователей)
CREATE ROLE BASE_ROLE;

GRANT CREATE SESSION TO BASE_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.USER_PACKAGE TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_PRODUCTS TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_PRICES TO BASE_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_SHOPS_INFO TO BASE_ROLE;

-- 3. Роль администратора магазина
CREATE ROLE SHOP_ADMIN_ROLE;

GRANT BASE_ROLE TO SHOP_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.SHOP_ADMIN_PACKAGE TO SHOP_ADMIN_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_ALL_COURIERS TO SHOP_ADMIN_ROLE;
GRANT SELECT ON HEAD_ADMIN.GET_ORDERS_INFO TO SHOP_ADMIN_ROLE;
GRANT SELECT ON HEAD_ADMIN.ADMIN_USERS TO SHOP_ADMIN_ROLE;

-- 4. Роль главного администратора
CREATE ROLE HEAD_ADMIN_ROLE;

GRANT BASE_ROLE TO HEAD_ADMIN_ROLE;
GRANT SHOP_ADMIN_ROLE TO HEAD_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.HEAD_ADMIN_PACKAGE TO HEAD_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.EXPORT_PRODUCTS_TO_JSON TO HEAD_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.IMPORT_PRODUCTS_FROM_JSON TO HEAD_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.EXPORT_ORDERS_TO_JSON TO HEAD_ADMIN_ROLE;

-- 5. Создание пользователей
GRANT BASE_ROLE TO CUSTOMER;
GRANT SHOP_ADMIN_ROLE TO SHOP_ADMIN;
GRANT HEAD_ADMIN_ROLE TO HEAD_ADMIN;

-- 7. Права на пакеты JSON
GRANT EXECUTE ON HEAD_ADMIN.EXPORT_PRODUCTS_TO_JSON TO HEAD_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.IMPORT_PRODUCTS_FROM_JSON TO HEAD_ADMIN_ROLE;
GRANT EXECUTE ON HEAD_ADMIN.EXPORT_ORDERS_TO_JSON TO HEAD_ADMIN_ROLE;

-- Проверка
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== СОЗДАНЫ ПОЛЬЗОВАТЕЛИ И РОЛИ ===');
    DBMS_OUTPUT.PUT_LINE('1. Профиль: USERS_PROFILE');
    DBMS_OUTPUT.PUT_LINE('2. Роли:');
    DBMS_OUTPUT.PUT_LINE('   - BASE_ROLE (клиенты)');
    DBMS_OUTPUT.PUT_LINE('   - SHOP_ADMIN_ROLE (администраторы магазинов)');
    DBMS_OUTPUT.PUT_LINE('   - HEAD_ADMIN_ROLE (главный администратор)');
    DBMS_OUTPUT.PUT_LINE('3. Пользователи:');
    DBMS_OUTPUT.PUT_LINE('   - CUSTOMER (пароль: CustomerPass123)');
    DBMS_OUTPUT.PUT_LINE('   - SHOP_ADMIN (пароль: ShopAdminPass123)');
    DBMS_OUTPUT.PUT_LINE('   - HEAD_ADMIN (уже существует)');
    DBMS_OUTPUT.PUT_LINE('4. Синонимы: USER_PACKAGE, SHOP_ADMIN_PACKAGE, HEAD_ADMIN_PACKAGE');
END;
/