-- 1. Пользователи с ролями
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_USERS AS
SELECT AU.ID, PD.FULL_NAME, PD.EMAIL, PD.PHONE_NUMBER, 
       TO_CHAR(PD.DATE_OF_BIRTH, 'DD-MM-YYYY') as DATE_OF_BIRTH,
       UR.ROLE_NAME, AU.PASSWORD_HASH
FROM HEAD_ADMIN.APP_USER AU
JOIN HEAD_ADMIN.PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID
JOIN HEAD_ADMIN.USER_ROLE UR ON AU.USER_ROLE = UR.ID;

-- 2. Магазины с администраторами
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_SHOPS_INFO AS
SELECT FS.ID, FS.SHOP_NAME, FS.ADDRESS, FS.PHONE, FS.EMAIL,
       TO_CHAR(FS.OPEN_TIME, 'HH24:MI') as OPEN_TIME,
       TO_CHAR(FS.CLOSE_TIME, 'HH24:MI') as CLOSE_TIME,
       TO_CHAR(FS.DELIVERY_START_TIME, 'HH24:MI') as DELIVERY_START_TIME,
       TO_CHAR(FS.DELIVERY_END_TIME, 'HH24:MI') as DELIVERY_END_TIME,
       SDO_UTIL.TO_GEOJSON(FS.LOCATION) as LOCATION,
       SDO_UTIL.TO_GEOJSON(FS.COVERAGE_AREA) as COVERAGE_AREA,
       PD.FULL_NAME as ADMIN_NAME,
       FS.IS_ACTIVE
FROM HEAD_ADMIN.FLOWER_SHOP FS
JOIN HEAD_ADMIN.APP_USER AU ON FS.SHOP_ADMIN_ID = AU.ID
JOIN HEAD_ADMIN.PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID;

-- 3. Все товары
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_PRODUCTS AS
SELECT ID, PRODUCT_NAME, BASE_PRICE, DESCRIPTION, PRODUCT_IMAGE
FROM HEAD_ADMIN.PRODUCT WHERE IS_ACTIVE = 1;

-- 4. Цены по размерам
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_PRICES AS
SELECT SC.ID as SIZE_ID, SC.SIZE_NAME, SC.ITEM_SIZE, SC.MARKUP,
       P.ID as PRODUCT_ID, P.PRODUCT_NAME,
       ROUND(P.BASE_PRICE * SC.MARKUP, 2) as FINAL_PRICE
FROM HEAD_ADMIN.SIZE_CATEGORY SC
CROSS JOIN HEAD_ADMIN.PRODUCT P
WHERE P.IS_ACTIVE = 1;

-- 5. Курьеры с данными
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_ALL_COURIERS AS
SELECT C.ID, PD.FULL_NAME, PD.PHONE_NUMBER, PD.EMAIL,
       C.VEHICLE_TYPE, C.SALARY, C.IS_ACTIVE, C.IS_AVAILABLE,
       FS.SHOP_NAME, FS.ID as SHOP_ID
FROM HEAD_ADMIN.COURIER C
JOIN HEAD_ADMIN.PERSONAL_DATA PD ON C.PERSONAL_DATA_ID = PD.ID
JOIN HEAD_ADMIN.FLOWER_SHOP FS ON C.FLOWER_SHOP_ID = FS.ID;

-- 6. Информация о корзинах
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_CART_INFO AS
SELECT CI.ID, CI.CART_ID, C.USER_ID, 
       P.ID as PRODUCT_ID, P.PRODUCT_NAME,
       SC.ID as SIZE_ID, SC.SIZE_NAME,
       ROUND(P.BASE_PRICE * SC.MARKUP, 2) as UNIT_PRICE,
       CI.QUANTITY,
       ROUND(P.BASE_PRICE * SC.MARKUP * CI.QUANTITY, 2) as SUBTOTAL
FROM HEAD_ADMIN.CART_ITEM CI
JOIN HEAD_ADMIN.PRODUCT_ITEM_INFO PII ON CI.ITEM_INFO_ID = PII.ID
JOIN HEAD_ADMIN.PRODUCT P ON PII.PRODUCT_ID = P.ID
JOIN HEAD_ADMIN.SIZE_CATEGORY SC ON PII.SIZE_ID = SC.ID
JOIN HEAD_ADMIN.CART C ON CI.CART_ID = C.ID;

-- 7. Информация о заказах
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_ORDERS_INFO AS
SELECT UO.ID, UO.ORDER_NUMBER, 
       TO_CHAR(UO.ORDER_DATE, 'DD.MM.YYYY HH24:MI') as ORDER_DATE,
       UO.USER_ID, PD_USER.FULL_NAME as CUSTOMER_NAME,
       PD_USER.PHONE_NUMBER as CUSTOMER_PHONE,
       UO.DELIVERY_ADDRESS, UO.STATUS, UO.TOTAL_AMOUNT,
       FS.ID as SHOP_ID, FS.SHOP_NAME,
       C.ID as COURIER_ID, PD_COURIER.FULL_NAME as COURIER_NAME
FROM HEAD_ADMIN.USER_ORDER UO
JOIN HEAD_ADMIN.APP_USER AU ON UO.USER_ID = AU.ID
JOIN HEAD_ADMIN.PERSONAL_DATA PD_USER ON AU.PERSONAL_DATA = PD_USER.ID
JOIN HEAD_ADMIN.FLOWER_SHOP FS ON UO.FLOWER_SHOP_ID = FS.ID
LEFT JOIN HEAD_ADMIN.COURIER C ON UO.COURIER_ID = C.ID
LEFT JOIN HEAD_ADMIN.PERSONAL_DATA PD_COURIER ON C.PERSONAL_DATA_ID = PD_COURIER.ID;

-- 8. Товары в заказах
CREATE OR REPLACE VIEW HEAD_ADMIN.GET_ORDER_ITEMS AS
SELECT OI.ID, OI.ORDER_ID, 
       P.ID as PRODUCT_ID, P.PRODUCT_NAME,
       SC.ID as SIZE_ID, SC.SIZE_NAME,
       OI.UNIT_PRICE, OI.QUANTITY, OI.SUBTOTAL
FROM HEAD_ADMIN.ORDER_ITEM OI
JOIN HEAD_ADMIN.PRODUCT_ITEM_INFO PII ON OI.ITEM_INFO_ID = PII.ID
JOIN HEAD_ADMIN.PRODUCT P ON PII.PRODUCT_ID = P.ID
JOIN HEAD_ADMIN.SIZE_CATEGORY SC ON PII.SIZE_ID = SC.ID;

-- 9. Администраторы магазинов
CREATE OR REPLACE VIEW HEAD_ADMIN.ADMIN_USERS AS
SELECT AU.ID, PD.FULL_NAME, PD.EMAIL, PD.PHONE_NUMBER,
       TO_CHAR(PD.DATE_OF_BIRTH, 'DD-MM-YYYY') as DATE_OF_BIRTH,
       UR.ROLE_NAME, FS.SHOP_NAME, FS.ID as SHOP_ID
FROM HEAD_ADMIN.APP_USER AU
JOIN HEAD_ADMIN.PERSONAL_DATA PD ON AU.PERSONAL_DATA = PD.ID
JOIN HEAD_ADMIN.USER_ROLE UR ON AU.USER_ROLE = UR.ID
LEFT JOIN HEAD_ADMIN.FLOWER_SHOP FS ON AU.ID = FS.SHOP_ADMIN_ID
WHERE UR.ROLE_NAME IN ('head_admin', 'shop_admin');

-- 10. Не назначенные администраторы
CREATE OR REPLACE VIEW HEAD_ADMIN.UNASSIGNED_ADMINS AS
SELECT ID, FULL_NAME, EMAIL, PHONE_NUMBER
FROM HEAD_ADMIN.ADMIN_USERS
WHERE SHOP_ID IS NULL AND ROLE_NAME = 'shop_admin';

-- Проверка
BEGIN
    DBMS_OUTPUT.PUT_LINE('=== СОЗДАНЫ ПРЕДСТАВЛЕНИЯ ===');
    DBMS_OUTPUT.PUT_LINE('1. GET_USERS');
    DBMS_OUTPUT.PUT_LINE('2. GET_SHOPS_INFO');
    DBMS_OUTPUT.PUT_LINE('3. GET_PRODUCTS');
    DBMS_OUTPUT.PUT_LINE('4. GET_PRICES');
    DBMS_OUTPUT.PUT_LINE('5. GET_ALL_COURIERS');
    DBMS_OUTPUT.PUT_LINE('6. GET_CART_INFO');
    DBMS_OUTPUT.PUT_LINE('7. GET_ORDERS_INFO');
    DBMS_OUTPUT.PUT_LINE('8. GET_ORDER_ITEMS');
    DBMS_OUTPUT.PUT_LINE('9. ADMIN_USERS');
    DBMS_OUTPUT.PUT_LINE('10. UNASSIGNED_ADMINS');
END;
/